stages:
  - preparation
  - build
  - test
  - deploy
  - release

include:
  - component: $CI_SERVER_FQDN/components/terraform/terraform-module-registry/fetch-vault-secret@~latest
    inputs:
      vault-path: gitlab/gitlab-token@kv
      vault-secret: GL_TOKEN
  - component: $CI_SERVER_FQDN/components/gitlab/semantic-release/semantic-release@~latest
    inputs:
      stage: preparation
  - component: $CI_SERVER_FQDN/components/terraform/terraform-module-registry/build@~latest
    inputs:
      stage: build
  - component: $CI_SERVER_FQDN/components/terraform/terraform-module-registry/kics-sast-iac@~latest
    inputs:
      stage: test
  - component: $CI_SERVER_FQDN/components/terraform/terraform-module-registry/deploy@2.92.0
    inputs:
      stage: deploy
